// packages/components-angular/src/data-summary-item/data-summary-item.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { LinkComponent } from '../link/link.component';

@Component({
  selector: 'rhc-data-summary-item',
  imports: [CommonModule, LinkComponent],
  templateUrl: './data-summary-item.component.html',
})
export class DataSummaryItemComponent {
  @Input() key: string = '';
  @Input() value: string = '';
  @Input() href?: string;
  @Input() target?: '_self' | '_blank' | '_parent' | '_top' | '_unfencedTop' = '_self';
  @Input() actionLabel?: string;
}

<div class="rhc-data-summary__item">
  <dt class="rhc-data-summary__item-key">
    {{ key }}
  </dt>
  <dd class="rhc-data-summary__item-value">
    {{ value }}
  </dd>
  @if (href && actionLabel) {
    <rhc-link [href]="href" [target]="target" class="rhc-data-summary__item-action">
      {{ actionLabel }}
    </rhc-link>
  }
</div>

// packages/components-react/src/DataSummaryItem.tsx
import clsx from 'clsx';
import { HTMLAttributes, PropsWithChildren, Ref } from 'react';
import { Link } from './Link';

export interface DataSummaryItemProps extends HTMLAttributes<HTMLDivElement> {
  itemKey: string;
  itemValue: string;
  href?: string;
  target?: '_self' | '_blank' | '_parent' | '_top' | '_unfencedTop';
  actionLabel?: string;
  ref?: Ref<HTMLDivElement>;
}

export function DataSummaryItem({
  ref,
  className,
  itemKey,
  itemValue,
  href,
  target = '_self',
  actionLabel,
  ...restProps
}: PropsWithChildren<DataSummaryItemProps>) {
  return (
    <div className={clsx('rhc-data-summary__item', className)} ref={ref} {...restProps}>
      <dt className="rhc-data-summary__item-key">{itemKey}</dt>
      <dd className="rhc-data-summary__item-value">{itemValue}</dd>
      {href && target && actionLabel && (
        <dd className="rhc-data-summary__item-action">
          <Link href={href} target={target}>
            {actionLabel}
          </Link>
        </dd>
      )}
    </div>
  );
}
