// packages/components-angular/src/footer/footer.component.ts
import { Component, Input } from '@angular/core';
import { ColumnLayoutComponent } from '../column-layout/column-layout.component';
import { HeadingComponent } from '../heading/heading.component';
import { type HeadingLevel } from '../heading/heading.component';
import { IconComponent } from '../icon/icon.component';
import { LinkListComponent } from '../link-list/link-list.component';
import { LinkListItemComponent } from '../link-list-item/link-list-item.component';
import { LinkListLinkComponent } from '../link-list-link/link-list-link.component';

export interface ColumnItem {
  label: string;
  href: string;
}

export interface Column {
  heading: string;
  appearanceLevel: HeadingLevel;
  items: ColumnItem[];
}

export interface subFooter {
  items: ColumnItem[];
}

@Component({
  selector: 'footer[rhc-footer]',
  imports: [
    IconComponent,
    HeadingComponent,
    ColumnLayoutComponent,
    LinkListComponent,
    LinkListItemComponent,
    LinkListLinkComponent,
  ],
  templateUrl: './footer.component.html',
})
export class FooterComponent {
  @Input() background?: string;
  @Input() preFooter?: boolean;
  @Input() preFooterMessage?: string;
  @Input() heading?: string;
  @Input() appearanceLevel: HeadingLevel = 3;
  @Input() columns?: Column[];
  @Input() backtotop?: boolean;
  @Input() subFooter?: subFooter;

  scrollBackToTop = (event: MouseEvent) => {
    event.preventDefault();
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };
}

@if (preFooter) {
  <div class="rhc-page-prefooter">
    @if (preFooterMessage) {
      <span class="rhc-page-prefooter__content">{{ preFooterMessage }}</span>
    }
  </div>
}

<footer
  [class]="
    'utrecht-page-footer rhc-page-footer' +
    (background ? ' rhc-page-footer--' + background : '') +
    (background === 'primary' ? ' rhc-page-footer--primary-filled' : '')
  "
>
  <div class="rhc-page-footer__content rhc-page-footer__wrapper">
    @if (heading) {
      <div class="rhc-page-footer__title">
        <rhc-heading [level]="3" [appearanceLevel]="appearanceLevel">{{ heading }}</rhc-heading>
      </div>
    }
    <rhc-column-layout>
      @for (column of columns; track $index) {
        <div class="rhc-page-footer__section">
          <rhc-heading [level]="3" [appearanceLevel]="column.appearanceLevel">{{ column.heading }}</rhc-heading>
          <rhc-link-list>
            @for (item of column.items; track $index) {
              <li rhc-link-list-item>
                <a rhc-link-list-link [href]="item.href">
                  <rhc-icon icon="chevron-right" />
                  {{ item.label }}
                </a>
              </li>
            }
          </rhc-link-list>
        </div>
      }
    </rhc-column-layout>
  </div>

  @if (backtotop || subFooter) {
    <div
      [class]="
        'rhc-page-subfooter' +
        (background ? ' rhc-page-footer--' + background : '') +
        (background === 'primary' ? ' rhc-page-footer--primary-filled' : '')
      "
    >
      <div class="rhc-page-subfooter__content rhc-page-footer__wrapper">
        <rhc-link-list>
          @for (subFooterItem of subFooter?.items; track $index) {
            <li rhc-link-list-item>
              <a rhc-link-list-link [href]="subFooterItem.href">
                <rhc-icon icon="chevron-right" />
                {{ subFooterItem.label }}
              </a>
            </li>
          }
        </rhc-link-list>

        @if (backtotop) {
          <a class="rhc-page-subfooter__backtotop" href="#">
            Terug naar boven <rhc-icon icon="pijl-omhoog" (click)="scrollBackToTop($event)"
          /></a>
        }
      </div>
    </div>
  }
</footer>

// packages/components-react/src/Footer.tsx
import { PageFooterProps, PageFooter as UtrechtPageFooter } from '@utrecht/component-library-react';
import clsx from 'clsx';
import { ForwardedRef, forwardRef, PropsWithChildren, ReactNode } from 'react';
import React from 'react';
import { ColumnLayout } from './ColumnLayout';
import { Heading, HeadingLevel } from './Heading';
import { Icon } from './Icon';

interface FooterProps extends PageFooterProps {
  heading?: ReactNode;
  appearanceLevel?: HeadingLevel;
  columns?: ColumnProps[];
  background?: 'primary-filled' | 'primary-outlined';
  backtotop?: boolean;
  subFooter?: ReactNode;
  preFooter?: boolean;
  preFooterMessage?: ReactNode;
}

interface ColumnProps {
  heading: ReactNode;
  appearanceLevel?: HeadingLevel;
  children: ReactNode;
}

const MAX_APPEARANCE_HEADING_LEVEL = 5;
const scrollBackToTop = (event: React.MouseEvent<HTMLAnchorElement>) => {
  event.preventDefault();
  window.scrollTo({ top: 0, behavior: 'smooth' });
};

export const Footer = forwardRef(
  (
    {
      preFooter,
      preFooterMessage,
      className,
      heading,
      appearanceLevel = 2,
      columns,
      backtotop,
      subFooter,
      children,
      background,
      ...restProps
    }: PropsWithChildren<FooterProps>,
    ref: ForwardedRef<HTMLDivElement>,
  ) => (
    <>
      {(preFooter || preFooterMessage) && (
        <div className="rhc-page-prefooter">
          <span className="rhc-page-prefooter__content">{preFooterMessage}</span>
        </div>
      )}

      <UtrechtPageFooter
        {...restProps}
        ref={ref}
        className={clsx(
          'rhc-page-footer',
          background ? `rhc-page-footer--${background}` : 'rhc-page-footer--primary-filled',
          className,
        )}
      >
        <div className="rhc-page-footer__content rhc-page-footer__wrapper">
          {heading && (
            <div className="rhc-page-footer__title" key={'heading'}>
              <Heading
                level={2}
                appearanceLevel={
                  appearanceLevel >= MAX_APPEARANCE_HEADING_LEVEL ? MAX_APPEARANCE_HEADING_LEVEL : appearanceLevel
                }
              >
                {heading}
              </Heading>
            </div>
          )}
          <ColumnLayout>
            {columns?.map(({ heading: columnHeading, children }: ColumnProps, index: number) => (
              <div className="rhc-page-footer__section" key={index}>
                <Heading
                  level={heading ? 3 : 2}
                  appearanceLevel={
                    appearanceLevel >= MAX_APPEARANCE_HEADING_LEVEL ? MAX_APPEARANCE_HEADING_LEVEL : appearanceLevel
                  }
                >
                  {columnHeading}
                </Heading>
                {children}
              </div>
            ))}
            {children}
          </ColumnLayout>
        </div>
        {(backtotop || subFooter) && (
          <div
            className={clsx(
              'rhc-page-subfooter',
              background ? `rhc-page-footer--${background}` : 'rhc-page-footer--primary-filled',
            )}
          >
            <div className="rhc-page-subfooter__content rhc-page-footer__wrapper">
              {backtotop && (
                <a className="rhc-page-subfooter__backtotop" href="#" onClick={scrollBackToTop}>
                  Terug naar boven <Icon icon="pijl-omhoog" />
                </a>
              )}
              {subFooter}
            </div>
          </div>
        )}
      </UtrechtPageFooter>
    </>
  ),
);

Footer.displayName = 'Footer';
