// packages/components-angular/src/button/button.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';

@Component({
  selector: 'rhc-button',
  imports: [CommonModule],
  templateUrl: './button.component.html',
})
export class ButtonComponent {
  @Input() appearance?: '' | 'primary-action' | 'secondary-action' | 'subtle' = '';
  @Input() disabled?: boolean = false;

  computedClasses = () => `utrecht-button utrecht-button--${this.appearance}`;
}

<button class="{{ computedClasses() }}" [disabled]="disabled">
  <ng-container [ngTemplateOutlet]="content"></ng-container>
</button>

<ng-template #content>
  <ng-content></ng-content>
</ng-template>

// packages/web-components-stencil/src/button.stencil.tsx
import { Component, h, Prop } from '@stencil/core';
import clsx from 'clsx';

@Component({
  tag: 'rhc-button',
  styleUrls: ['button.scss', 'index.scss'],
  shadow: true,
})
export class Button {
  @Prop() appearance?: string;
  @Prop() busy?: boolean;
  @Prop() disabled?: boolean;
  @Prop() type?: string;
  @Prop() hint?: string;
  @Prop() pressed?: boolean;

  render() {
    const { busy, disabled, type, hint, pressed, appearance } = this;

    return (
      <button
        class={clsx(
          'utrecht-button',
          busy && 'utrecht-button--busy',
          disabled && 'utrecht-button--disabled',
          type === 'submit' && 'utrecht-button--submit',
          appearance === 'primary-action-button' && 'utrecht-button--primary-action',
          appearance === 'secondary-action-button' && 'utrecht-button--secondary-action',
          appearance === 'subtle-button' && 'utrecht-button--subtle',
          hint === 'danger' && 'utrecht-button--danger',
          hint === 'warning' && 'utrecht-button--warning',
          hint === 'ready' && 'utrecht-button--ready',
          pressed && 'utrecht-button--pressed',
        )}
      >
        <slot />
      </button>
    );
  }
}
