// packages/components-react/src/Hero.tsx
import clsx from 'clsx';
import { ForwardedRef, forwardRef, HTMLAttributes, PropsWithChildren, ReactNode } from 'react';
import { Heading } from './Heading';
import { HeadingGroup } from './HeadingGroup';
import { Image } from './Image';
import { Paragraph } from './Paragraph';

export interface HeroProps extends HTMLAttributes<HTMLDivElement> {
  textAlign?: 'start' | 'end';
  imageSrc: string;
  imageAlt: string;
  heading?: ReactNode;
  headingLevel?: 1 | 2 | 3 | 4 | 5;
  subHeading?: ReactNode;
  heroMessage?: boolean;
  aspectRatio?: '16 / 9' | '1 / 1' | '4 / 3';
  borderRadiusCorner?: 'start-start' | 'start-end' | 'end-start' | 'end-end';
}

export const Hero = forwardRef(
  (
    {
      textAlign = 'start',
      children,
      className,
      imageSrc,
      imageAlt,
      heading,
      subHeading,
      heroMessage,
      headingLevel = 3,
      borderRadiusCorner,
      aspectRatio = '16 / 9',
      ...restProps
    }: PropsWithChildren<HeroProps>,
    ref: ForwardedRef<HTMLDivElement>,
  ) => {
    return (
      <div
        ref={ref}
        className={clsx(
          'rhc-hero',
          heroMessage && `rhc-hero--text-align-${textAlign}`,
          heroMessage &&
            borderRadiusCorner &&
            `rhc-hero--custom-border-radius-corner rhc-hero--border-radius-corner-${borderRadiusCorner}`,
          `rhc-hero--aspect-ratio-${aspectRatio.replace(' / ', '-')}`,
          className,
        )}
        {...restProps}
      >
        <Image alt={imageAlt} className="rhc-hero__image" src={imageSrc} />
        {heroMessage && (
          <div className={clsx('rhc-hero__message')}>
            <HeadingGroup>
              <Heading appearance="utrecht-heading-3" className="rhc-hero__heading" level={headingLevel}>
                {heading}
              </Heading>
              <Paragraph className="rhc-hero__sub-heading">{subHeading}</Paragraph>
            </HeadingGroup>
          </div>
        )}
        {children && <div className="rhc-hero__children">{children}</div>}
      </div>
    );
  },
);

Hero.displayName = 'Hero';

// packages/web-components-stencil/src/hero.stencil.tsx
import { Component, h, Prop } from '@stencil/core';
import clsx from 'clsx';

@Component({
  tag: 'rhc-hero',
  styleUrl: 'hero.scss',
  shadow: true,
})
export class Hero {
  @Prop() aspectRatio?: '16-9' | '1-1' | '4-3' = '16-9';
  @Prop() textAlign?: 'start' | 'center' | 'end' = 'start';
  @Prop() borderRadiusCorner?: 'start-start' | 'start-end' | 'end-start' | 'end-end';
  @Prop() imageSrc?: string;
  @Prop() imageAlt?: string;
  @Prop() heading?: string;
  @Prop() headingLevel?: 1 | 2 | 3 | 4 | 5 = 3;
  @Prop() subHeading?: string;
  @Prop() heroMessage?: boolean;
  @Prop() customName?: string;

  render() {
    const {
      aspectRatio,
      textAlign,
      borderRadiusCorner,
      imageSrc,
      imageAlt,
      heading,
      subHeading,
      heroMessage,
      customName,
      headingLevel,
    } = this;

    return (
      <div class="rhc-hero">
        <div
          class={clsx(
            'rhc-hero',
            heroMessage && `rhc-hero--text-align-${textAlign}`,
            heroMessage &&
              borderRadiusCorner &&
              `rhc-hero--custom-border-radius-corner rhc-hero--border-radius-corner-${borderRadiusCorner}`,
            `rhc-hero--aspect-ratio-${aspectRatio?.replace(' / ', '-')}`,
            customName,
          )}
        >
          <img class="rhc-hero__image" src={imageSrc} alt={imageAlt} />
          {heroMessage && (
            <div class="rhc-hero__message">
              <div>
                <h3
                  class={clsx(`rhc-hero__heading`, {
                    [`utrecht-heading-${headingLevel}`]: headingLevel,
                  })}
                >
                  {heading}
                </h3>
                <p class="rhc-hero__sub-heading utrecht-paragraph">{subHeading}</p>
              </div>
            </div>
          )}
        </div>
      </div>
    );
  }
}
