// packages/web-components-stencil/src/hero.stencil.tsx
import { Component, h, Prop } from '@stencil/core';
import clsx from 'clsx';

@Component({
  tag: 'rhc-hero',
  styleUrl: 'hero.scss',
  shadow: true,
})
export class Hero {
  @Prop() aspectRatio?: '16-9' | '1-1' | '4-3' = '16-9';
  @Prop() textAlign?: 'start' | 'center' | 'end' = 'start';
  @Prop() borderRadiusCorner?: 'start-start' | 'start-end' | 'end-start' | 'end-end';
  @Prop() imageSrc?: string;
  @Prop() imageAlt?: string;
  @Prop() heading?: string;
  @Prop() headingLevel?: 1 | 2 | 3 | 4 | 5 = 3;
  @Prop() subHeading?: string;
  @Prop() heroMessage?: boolean;
  @Prop() customName?: string;

  render() {
    const {
      aspectRatio,
      textAlign,
      borderRadiusCorner,
      imageSrc,
      imageAlt,
      heading,
      subHeading,
      heroMessage,
      customName,
      headingLevel,
    } = this;

    return (
      <div class="rhc-hero">
        <div
          class={clsx(
            'rhc-hero',
            heroMessage && `rhc-hero--text-align-${textAlign}`,
            heroMessage &&
              borderRadiusCorner &&
              `rhc-hero--custom-border-radius-corner rhc-hero--border-radius-corner-${borderRadiusCorner}`,
            `rhc-hero--aspect-ratio-${aspectRatio?.replace(' / ', '-')}`,
            customName,
          )}
        >
          <img class="rhc-hero__image" src={imageSrc} alt={imageAlt} />
          {heroMessage && (
            <div class="rhc-hero__message">
              <div>
                <h3
                  class={clsx(`rhc-hero__heading`, {
                    [`utrecht-heading-${headingLevel}`]: headingLevel,
                  })}
                >
                  {heading}
                </h3>
                <p class="rhc-hero__sub-heading utrecht-paragraph">{subHeading}</p>
              </div>
            </div>
          )}
        </div>
      </div>
    );
  }
}

// packages/components-react/library-react/src/Hero.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2026 Community for NL Design System
 */

import clsx from 'clsx';
import { HTMLAttributes, PropsWithChildren, ReactNode, Ref } from 'react';
import { Paragraph } from '.';
import { Image } from '.';
import { Heading, HeadingLevel } from './Heading';
import { HeadingGroup } from './HeadingGroup';


export interface HeroBaseProps extends HTMLAttributes<HTMLDivElement> {
  textAlign?: 'start' | 'end';
  imageSrc: string;
  imageAlt?: string;
  imagePresentation?: boolean;
  headingLevel?: HeadingLevel;
  headingAppearanceLevel?: HeadingLevel;
  aspectRatio?: '16 / 9' | '1 / 1' | '4 / 3';
  borderRadiusCorner?: 'start-start' | 'start-end' | 'end-start' | 'end-end';
  ref?: Ref<HTMLDivElement>;
}

export interface HeroWithHeading extends HeroBaseProps {
  heading: ReactNode;
  subHeading?: ReactNode;
}

export interface HeroWithoutSubHeading extends HeroBaseProps {
  heading?: ReactNode;
  subHeading?: never;
}

export type HeroProps = HeroWithHeading | HeroWithoutSubHeading;

export const Hero = ({
  ref,
  textAlign = 'start',
  children,
  className,
  imageSrc,
  imageAlt,
  imagePresentation,
  heading,
  subHeading,
  headingLevel = 3,
  headingAppearanceLevel = headingLevel,
  borderRadiusCorner,
  aspectRatio = '16 / 9',
  ...restProps
}: PropsWithChildren<HeroProps>) => {
  return (
    <section
      ref={ref}
      className={clsx(
        'rhc-hero',
        heading && `rhc-hero--text-align-${textAlign}`,
        heading &&
          borderRadiusCorner &&
          `rhc-hero--custom-border-radius-corner rhc-hero--border-radius-corner-${borderRadiusCorner}`,
        `rhc-hero--aspect-ratio-${aspectRatio.replace(' / ', '-')}`,
        className,
      )}
      {...restProps}
    >
      <Image alt={imageAlt} className="rhc-hero__image" presentation={imagePresentation} src={imageSrc} />
      {heading && (
        <div className={clsx('rhc-hero__message')}>
          <HeadingGroup>
            <Heading appearanceLevel={headingAppearanceLevel} className="rhc-hero__heading" level={headingLevel}>
              {heading}
            </Heading>
            {subHeading && <Paragraph className="rhc-hero__sub-heading">{subHeading}</Paragraph>}
          </HeadingGroup>
        </div>
      )}
      {children && <div className="rhc-hero__children">{children}</div>}
    </section>
  );
};

Hero.displayName = 'Hero';
