// packages/components-react/footer-react/src/Footer.tsx
/**
 * @license EUPL-1.2
 * Copyright (c) 2026 Community for NL Design System
 */

import { ColumnLayout } from '@rijkshuisstijl-community/column-layout-react/no-side-effects';
import { Heading, HeadingLevel } from '@rijkshuisstijl-community/heading-react/no-side-effects';
import { Icon } from '@rijkshuisstijl-community/icon-react/no-side-effects';
import { Link } from '@rijkshuisstijl-community/link-react/no-side-effects';
import clsx from 'clsx';
import { HTMLAttributes, MouseEvent, PropsWithChildren, ReactNode, Ref } from 'react';

interface FooterProps extends HTMLAttributes<HTMLDivElement> {
  heading?: ReactNode;
  headingId?: string;
  appearanceLevel?: HeadingLevel;
  columns?: ColumnProps[];
  background?: 'primary-filled' | 'primary-outlined';
  backtotop?: boolean;
  subFooter?: ReactNode;
  preFooter?: boolean;
  preFooterMessage?: ReactNode;
  ref?: Ref<HTMLDivElement>;
  tagline?: ReactNode;
}

interface ColumnProps {
  heading: ReactNode;
  appearanceLevel?: HeadingLevel;
  children: ReactNode;
}

const scrollBackToTop = (event: MouseEvent<HTMLAnchorElement>) => {
  event.preventDefault();
  window.scrollTo({ top: 0, behavior: 'smooth' });
  const target = event.currentTarget.getAttribute('href');
  if (!target) return;
  const $target = document.querySelector(target) as HTMLElement;
  if (!$target) return;
  $target.focus({ preventScroll: true }); // Ensure target is focusable, ie via tabindex={-1} on #main
};

export const Footer = ({
  preFooter,
  ref,
  preFooterMessage,
  className,
  heading,
  headingId = 'page-footer-heading',
  appearanceLevel = 3,
  columns,
  backtotop,
  subFooter,
  children,
  background,
  tagline,
  ...restProps
}: PropsWithChildren<FooterProps>) => (
  <footer aria-labelledby={heading ? headingId : undefined} className="rhc-page-footer-container">
    {preFooter && (
      <div className="rhc-page-prefooter">
        {preFooterMessage && <span className="rhc-page-prefooter__content">{preFooterMessage}</span>}
      </div>
    )}

    <div
      {...restProps}
      ref={ref}
      className={clsx(
        'utrecht-page-footer',
        'rhc-page-footer',
        background ? `rhc-page-footer--${background}` : 'rhc-page-footer--primary-filled',
        className,
      )}
    >
      <div className="utrecht-page-footer__content">
        {heading ? (
          <Heading hidden aria-hidden="true" id={headingId} level={2}>
            {heading}
          </Heading>
        ) : null}
        <div className="rhc-page-footer-layout">
          {tagline && (
            <div className="rhc-page-footer__tagline" key={'heading'}>
              <Heading appearanceLevel={appearanceLevel} level={2} role="presentation">
                {tagline}
              </Heading>
            </div>
          )}
          <ColumnLayout>
            {columns?.map(({ heading: columnHeading, children }: ColumnProps, index: number) => (
              <div className="rhc-page-footer__section" key={index}>
                <Heading appearanceLevel={appearanceLevel} level={heading ? 3 : 2}>
                  {columnHeading}
                </Heading>
                {children}
              </div>
            ))}
            {children}
          </ColumnLayout>
        </div>
      </div>
    </div>
    {(backtotop || subFooter) && (
      <div
        className={clsx(
          'utrecht-page-footer',
          'rhc-page-footer',
          'rhc-page-footer--subfooter',
          background ? `rhc-page-footer--${background}` : 'rhc-page-footer--primary-filled',
        )}
      >
        <div className="utrecht-page-footer__content">
          <div className="rhc-page-subfooter-layout">
            {subFooter}
            {backtotop && (
              <Link href="#main" onClick={scrollBackToTop}>
                Terug naar boven <Icon icon="pijl-omhoog" />
              </Link>
            )}
          </div>
        </div>
      </div>
    )}
  </footer>
);

Footer.displayName = 'Footer';

// packages/components-angular/src/footer/footer.component.ts
import { Component, Input } from '@angular/core';
import { ColumnLayoutComponent } from '../column-layout/column-layout.component';
import { HeadingComponent } from '../heading/heading.component';
import { type HeadingLevel } from '../heading/heading.component';
import { IconComponent } from '../icon/icon.component';
import { LinkListComponent } from '../link-list/link-list.component';
import { LinkListItemComponent } from '../link-list-item/link-list-item.component';
import { LinkListLinkComponent } from '../link-list-link/link-list-link.component';

@Component({
  selector: 'footer[rhc-footer]',
  imports: [
    IconComponent,
    HeadingComponent,
    ColumnLayoutComponent,
    LinkListComponent,
    LinkListItemComponent,
    LinkListLinkComponent,
  ],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css',
})
export class FooterComponent {
  @Input() background?: string;
  @Input() preFooter?: boolean;
  @Input() preFooterMessage?: string;
  @Input() heading?: string;
  @Input() appearanceLevel: HeadingLevel = 3;
  @Input() backtotop?: boolean;

  scrollBackToTop = (event: MouseEvent) => {
    event.preventDefault();
    window.scrollTo({ top: 0, behavior: 'smooth' });
    const targetElement = event.currentTarget as HTMLAnchorElement;
    const targetSelector = targetElement.getAttribute('href');
    if (!targetSelector) return;
    const $target = document.querySelector(targetSelector) as HTMLElement | null;
    if (!$target) return;
    $target.focus({ preventScroll: true }); // Ensure target is focusable, ie via tabindex={-1} on #main
  };
}

@if (preFooter) {
  <div class="rhc-page-prefooter">
    @if (preFooterMessage) {
      <span class="rhc-page-prefooter__content">{{ preFooterMessage }}</span>
    }
  </div>
}

<footer
  [class]="
    'utrecht-page-footer rhc-page-footer' +
    (background ? ' rhc-page-footer--' + background : '') +
    (background === 'primary' ? ' rhc-page-footer--primary-filled' : '')
  "
>
  <div class="rhc-page-footer__content rhc-page-footer__wrapper">
    @if (heading) {
      <div class="rhc-page-footer__title">
        <rhc-heading [level]="3" [appearanceLevel]="appearanceLevel">{{ heading }}</rhc-heading>
      </div>
    }
    <rhc-column-layout>
      @for (column of columns; track $index) {
        <div class="rhc-page-footer__section">
          <rhc-heading [level]="3" [appearanceLevel]="column.appearanceLevel">{{ column.heading }}</rhc-heading>
          <rhc-link-list>
            @for (item of column.items; track $index) {
              <li rhc-link-list-item>
                <a rhc-link-list-link [href]="item.href">
                  <rhc-icon icon="chevron-right" />
                  {{ item.label }}
                </a>
              </li>
            }
          </rhc-link-list>
        </div>
      }
    </rhc-column-layout>
  </div>

  @if (backtotop || subFooter) {
    <div
      [class]="
        'rhc-page-subfooter' +
        (background ? ' rhc-page-footer--' + background : '') +
        (background === 'primary' ? ' rhc-page-footer--primary-filled' : '')
      "
    >
      <div class="rhc-page-subfooter__content rhc-page-footer__wrapper">
        <rhc-link-list>
          @for (subFooterItem of subFooter?.items; track $index) {
            <li rhc-link-list-item>
              <a rhc-link-list-link [href]="subFooterItem.href">
                <rhc-icon icon="chevron-right" />
                {{ subFooterItem.label }}
              </a>
            </li>
          }
        </rhc-link-list>

        @if (backtotop) {
          <a class="rhc-page-subfooter__backtotop" href="#">
            Terug naar boven <rhc-icon icon="pijl-omhoog" (click)="scrollBackToTop($event)"
          /></a>
        }
      </div>
    </div>
  }
</footer>
